### ISSUE TITLE
panic: test timed out after 10s

### ISSUE THREAD

**Issue by devimc** [kata-containers/tests#225]
Randomly unit tests are killed if timeout is reached out, this issue can be reproduced easily on systems running low on resources like azure VMs.

```
=== RUN   TestWaitForShimRunningForTooLongFailure
panic: test timed out after 10s

goroutine 648 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1145 +0x139
created by time.goFunc
	/usr/local/go/src/time/sleep.go:170 +0x52

goroutine 1 [chan receive, locked to thread]:
testing.(*T).Run(0xc4201d6000, 0xf36f0e, 0x27, 0xf4f198, 0xc42005d701)
	/usr/local/go/src/testing/testing.go:790 +0x59b
testing.runTests.func1(0xc4201d6000)
	/usr/local/go/src/testing/testing.go:1004 +0xa8
testing.tRunner(0xc4201d6000, 0xc42005d920)
	/usr/local/go/src/testing/testing.go:746 +0x16d
testing.runTests(0xc420180540, 0x15b3740, 0x1a4, 0x1a4, 0x0)
	/usr/local/go/src/testing/testing.go:1002 +0x522
testing.(*M).Run(0xc42005df20, 0x2)
	/usr/local/go/src/testing/testing.go:921 +0x207
github.com/kata-containers/runtime/virtcontainers.TestMain(0xc42005df20)
	/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers/virtcontainers_test.go:147 +0x1983
main.main()
	github.com/kata-containers/runtime/virtcontainers/_test/_testmain.go:1022 +0x2f1

goroutine 47 [runnable]:
github.com/kata-containers/runtime/virtcontainers/pkg/mock.(*ccProxyProtocol).Handle(...)
	/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers/pkg/mock/cc_proxy_mock.go:385
github.com/kata-containers/runtime/virtcontainers/pkg/mock.(*CCProxyMock).serve(0xc42021e090)
	/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers/pkg/mock/cc_proxy_mock.go:267 +0x210
github.com/kata-containers/runtime/virtcontainers/pkg/mock.(*CCProxyMock).Start.func1(0xc42021e090)
	/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers/pkg/mock/cc_proxy_mock.go:302 +0x39
created by github.com/kata-containers/runtime/virtcontainers/pkg/mock.(*CCProxyMock).Start
	/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers/pkg/mock/cc_proxy_mock.go:300 +0x5b

goroutine 362 [select]:
github.com/kata-containers/runtime/vendor/google.golang.org/grpc.(*ccResolverWrapper).watcher(0xc420224a20)
	/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:99 +0x22f
created by github.com/kata-containers/runtime/vendor/google.golang.org/grpc.newCCResolverWrapper
	/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:84 +0x4fd

goroutine 79 [runnable]:
github.com/kata-containers/runtime/virtcontainers/pkg/mock.(*CCProxyMock).serve(0xc42021e120)
	/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers/pkg/mock/cc_proxy_mock.go:261 +0xb3a
github.com/kata-containers/runtime/virtcontainers/pkg/mock.(*CCProxyMock).Start.func1(0xc42021e120)
	/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers/pkg/mock/cc_proxy_mock.go:302 +0x39
created by github.com/kata-containers/runtime/virtcontainers/pkg/mock.(*CCProxyMock).Start
	/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers/pkg/mock/cc_proxy_mock.go:300 +0x5b

goroutine 668 [sleep]:
time.Sleep(0x5f5e100)
	/usr/local/go/src/runtime/time.go:65 +0x133
github.com/kata-containers/runtime/virtcontainers.waitForShim(0x1765b, 0xc4201026e0, 0xc42b79f30f)
	github.com/kata-containers/runtime/virtcontainers/_test/_obj_test/shim.go:319 +0xca
github.com/kata-containers/runtime/virtcontainers.TestWaitForShimRunningForTooLongFailure(0xc4203891d0)
	/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers/shim_test.go:282 +0xba
testing.tRunner(0xc4203891d0, 0xf4f198)
	/usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x569
```

**Comment by bergwolf** [comment]
Another occurrence http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-runtime-centos-7-4-PR/11/console

**Comment by chavafg** [comment]
The timeout failure occurs on different tests:
`TestSocketsSetFailingVoidArguments` from @bergwolf comment above.

```
--- PASS: TestSpawnerTypeSet (0.00s)
panic: test timed out after 10s
```
from  http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-runtime-ubuntu-16-04-PR/211/console

```
--- PASS: TestQemuAmd64CPUModel (0.00s)
panic: test timed out after 10s
```
from http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-runtime-ubuntu-16-04-PR/202/console 


```
=== RUN   TestIsPhysicalIface
panic: test timed out after 10s
```
from http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-runtime-ubuntu-17-10-PR/43/console

```
=== RUN   TestMajorMinorNumber
panic: test timed out after 10s
```
from http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-runtime-ubuntu-17-10-PR/41/console

**Comment by sboeuf** [comment]
Sorry I could not look into this today, I'll take a look tomorrow first thing !

**Comment by devimc** [comment]
Fixed in https://github.com/kata-containers/runtime/pull/209
