### ISSUE TITLE
Power 8 CI not running on kata 1.x

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#3434]
It seems that the Power 8 CI is not being triggered when somebody is testing a PR in kata 1.x, I see 
```
[04/20/21 16:23:56] [SSH] Opening SSH connection.
[04/20/21 16:23:56] [SSH] WARNING: SSH Host Keys are not being verified. Man-in-the-middle attacks may be possible against this connection.
ERROR: Server rejected the 1 private key(s) for jenkins
ERROR: Failed to authenticate as jenkins with credential
java.io.IOException: Publickey authentication failed.
	at com.trilead.ssh2.auth.AuthenticationManager.authenticatePublicKey(AuthenticationManager.java:349)
	at com.trilead.ssh2.Connection.authenticateWithPublicKey(Connection.java:472)
	at com.cloudbees.jenkins.plugins.sshcredentials.impl.TrileadSSHPublicKeyAuthenticator.doAuthenticate(TrileadSSHPublicKeyAuthenticator.java:109)
	at com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticator.authenticate(SSHAuthenticator.java:436)
	at com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticator.authenticate(SSHAuthenticator.java:473)
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:865)
	at hudson.plugins.sshslaves.SSHLauncher$1.call(SSHLauncher.java:436)
	at hudson.plugins.sshslaves.SSHLauncher$1.call(SSHLauncher.java:423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: The connection is closed.
	at com.trilead.ssh2.auth.AuthenticationManager.deQueue(AuthenticationManager.java:72)
	at com.trilead.ssh2.auth.AuthenticationManager.getNextMessage(AuthenticationManager.java:100)
	at com.trilead.ssh2.auth.AuthenticationManager.authenticatePublicKey(AuthenticationManager.java:324)
	... 11 more
Caused by: java.io.IOException: Cannot read full block, EOF reached.
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.getBlock(CipherInputStream.java:81)
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.read(CipherInputStream.java:108)
	at com.trilead.ssh2.transport.TransportConnection.receiveMessage(TransportConnection.java:232)
	at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:706)
	at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:502)
	... 1 more
[04/20/21 16:23:56] [SSH] Authentication failed.
```
/cc @bpradipt

**Comment by bpradipt** [comment]
@GabyCT we are in the process of reinstalling the server due to an exposure.
cc @chavafg

**Comment by chavafg** [comment]
@bpradipt thanks for letting us know.
@GabyCT could you help us remove the required flag from those jobs while the server is reinstalled?

**Comment by GabyCT** [comment]
@chavafg as I saw Power 8 is not required currently in kata 1.x

**Comment by bpradipt** [comment]
@GabyCT yes, we'll add a Power9 server for Kata 2.x CI.

**Comment by ariel-adam** [comment]
Closing this issue since we are moving to the kata 2.x CI instead.
