### ISSUE TITLE
ARM doesn't support data rlimit

### ISSUE THREAD

**Issue by devimc** [kata-containers/tests#990]
```
• [SLOW TEST:8.022 seconds]
ulimits
/home/jenkins/workspace/kata-containers-tests-ARM-18.04-PR/go/src/github.com/kata-containers/tests/integration/docker/ulimit_test.go:28
  check ulimits
  /home/jenkins/workspace/kata-containers-tests-ARM-18.04-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
    Checking ulimit fsize=67584:83968, expects soft=66 and hard=82
    /home/jenkins/workspace/kata-containers-tests-ARM-18.04-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46

------------------------------
ulimits check ulimits
  Checking ulimit data=102400000:122880000, expects soft=100000 and hard=120000
  /home/jenkins/workspace/kata-containers-tests-ARM-18.04-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
Running command '/usr/bin/docker [docker run --cidfile /tmp/cid198354779/x05UQQXNDZzZsKxpGn3DPXuzQjfhv4 --runtime kata-runtime --name x05UQQXNDZzZsKxpGn3DPXuzQjfhv4 --rm --
ulimit data=102400000:122880000 centos bash -c echo $(ulimit -d -S):$(ulimit -d -H)]'
command failed error 'exit status 125'
[docker run --cidfile /tmp/cid198354779/x05UQQXNDZzZsKxpGn3DPXuzQjfhv4 --runtime kata-runtime --name x05UQQXNDZzZsKxpGn3DPXuzQjfhv4 --rm --ulimit data=102400000:122880000 c
entos bash -c echo $(ulimit -d -S):$(ulimit -d -H)]
Timeout: 60 seconds
Exit Code: 125
Stdout:
Stderr: runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f9a6cb97c m=3 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f9a6cb97c
stack: frame={sp:0x7f97c26300, fp:0x0} stack=[0x7f97426d38,0x7f97c26938)
0000007f97c26200:  0000007f97c26260  0000007f9a86df54
0000007f97c26210:  0000007f97c26348  0000000000000001
0000007f97c26220:  0000000000000213  0000007f9a69b2a8
0000007f97c26230:  0000007f9a894000  0000000000000001
0000007f97c26240:  0000007f9a88d9c0  0000007f97c26348
0000007f97c26250:  0000007f97c26344  0000000000000000
0000007f97c26260:  0000007f97c26370  0000007f9a86e800
0000007f97c26270:  000000000f11ed7d  0000007f9a8964c8
0000007f97c26280:  000000558e12a6e0  0000007f97c26488
0000007f97c26290:  0000007f9a88dfc0  0000000000000005
0000007f97c262a0:  0000007f9a896170  0000000000000000
0000007f97c262b0:  0000007f97c26408  0000007f97c26418
0000007f97c262c0:  0000000000000000  0000000000000001
0000007f97c262d0:  0000007f9a88dfc0  0000007f97c26348
0000007f97c262e0:  0000007f9a6aa330  00000000003c47b5
0000007f97c262f0:  000000558e12a6e0  0000007f97c26344
0000007f97c26300: <0000007f97c26430  0000007f9a6b9568
0000007f97c26310:  0000007f9a80a000  0000007f97c271e0
0000007f97c26320:  0000007f9a88df60  0000000000000000
0000007f97c26330:  0000000000000005  0000000000000001
0000007f97c26340:  000000000000085b  0000000000000000
0000007f97c26350:  0000007f00000005  0000000000000000
0000007f97c26360:  0000007f00000001  0000007f9a896170
0000007f97c26370:  0000007f97c26430  0000007f9a6b9510
0000007f97c26380:  0000007f9a80a000  0000007f97c271e0
0000007f97c26390:  0000007f97c26710  00000055bb0f8460
0000007f97c263a0:  0000000000001000  fffffffe7fffffff
0000007f97c263b0:  ffffffffffffffff  ffffffffffffffff
0000007f97c263c0:  ffffffffffffffff  ffffffffffffffff
0000007f97c263d0:  ffffffffffffffff  ffffffffffffffff
0000007f97c263e0:  ffffffffffffffff  ffffffffffffffff
0000007f97c263f0:  ffffffffffffffff  ffffffffffffffff
runtime: unknown pc 0x7f9a6cb97c
stack: frame={sp:0x7f97c26300, fp:0x0} stack=[0x7f97426d38,0x7f97c26938)
0000007f97c26200:  0000007f97c26260  0000007f9a86df54
0000007f97c26210:  0000007f97c26348  0000000000000001
0000007f97c26220:  0000000000000213  0000007f9a69b2a8
0000007f97c26230:  0000007f9a894000  0000000000000001
0000007f97c26240:  0000007f9a88d9c0  0000007f97c26348
0000007f97c26250:  0000007f97c26344  0000000000000000
0000007f97c26260:  0000007f97c26370  0000007f9a86e800
0000007f97c26270:  000000000f11ed7d  0000007f9a8964c8
0000007f97c26280:  000000558e12a6e0  0000007f97c26488
0000007f97c26290:  0000007f9a88dfc0  0000000000000005
0000007f97c262a0:  0000007f9a896170  0000000000000000
0000007f97c262b0:  0000007f97c26408  0000007f97c26418
0000007f97c262c0:  0000000000000000  0000000000000001
0000007f97c262d0:  0000007f9a88dfc0  0000007f97c26348
0000007f97c262e0:  0000007f9a6aa330  00000000003c47b5
0000007f97c262f0:  000000558e12a6e0  0000007f97c26344
0000007f97c26300: <0000007f97c26430  0000007f9a6b9568
0000007f97c26310:  0000007f9a80a000  0000007f97c271e0
0000007f97c26320:  0000007f9a88df60  0000000000000000
0000007f97c26330:  0000000000000005  0000000000000001
0000007f97c26340:  000000000000085b  0000000000000000
0000007f97c26350:  0000007f00000005  0000000000000000
0000007f97c26360:  0000007f00000001  0000007f9a896170
0000007f97c26370:  0000007f97c26430  0000007f9a6b9510
0000007f97c26380:  0000007f9a80a000  0000007f97c271e0
0000007f97c26390:  0000007f97c26710  00000055bb0f8460
0000007f97c263a0:  0000000000001000  fffffffe7fffffff
0000007f97c263b0:  ffffffffffffffff  ffffffffffffffff
0000007f97c263c0:  ffffffffffffffff  ffffffffffffffff
0000007f97c263d0:  ffffffffffffffff  ffffffffffffffff
0000007f97c263e0:  ffffffffffffffff  ffffffffffffffff
0000007f97c263f0:  ffffffffffffffff  ffffffffffffffff
goroutine 5 [syscall]:
runtime.notetsleepg(0x558f1b5e40, 0xffffffffffffffff, 0x558e976410)
	/usr/go/src/runtime/lock_futex.go:227 +0x28 fp=0x400004a780 sp=0x400004a750 pc=0x558e483a20
os/signal.signal_recv(0x4000000000)
	/usr/go/src/runtime/sigqueue.go:139 +0xb8 fp=0x400004a7a0 sp=0x400004a780 pc=0x558e4b8380
os/signal.loop()
	/usr/go/src/os/signal/signal_unix.go:23 +0x18 fp=0x400004a7d0 sp=0x400004a7a0 pc=0x558e5a2bd0
runtime.goexit()
	/usr/go/src/runtime/asm_arm64.s:1114 +0x4 fp=0x400004a7d0 sp=0x400004a7d0 pc=0x558e4cd18c
created by os/signal.init.0
	/usr/go/src/os/signal/signal_unix.go:29 +0x30

goroutine 1 [runnable, locked to thread]:
syscall.Syscall6(0x38, 0xffffffffffffff9c, 0x4000179730, 0x80001, 0x0, 0x0, 0x0, 0x3, 0x4000179730, 0x0)
	/usr/go/src/syscall/asm_linux_arm64.s:35 +0x8
github.com/kata-containers/agent/vendor/golang.org/x/sys/unix.openat(0xffffffffffffff9c, 0x4000179720, 0xf, 0x80001, 0x4000000000, 0xf, 0xf, 0x4000179720)
	/home/jenkins/workspace/kata-containers-tests-ARM-18.04-PR/go/src/github.com/kata-containers/agent/vendor/golang.org/x/sys/unix/zsyscall_linux_arm64.go:68 +0x74
github.com/kata-containers/agent/vendor/golang.org/x/sys/unix.Open(0x4000179720, 0xf, 0x80001, 0x0, 0x1, 0x4000179720, 0xf)
	/home/jenkins/workspace/kata-containers-tests-ARM-18.04-PR/go/src/github.com/kata-containers/agent/vendor/golang.org/x/sys/unix/syscall_linux.go:107 +0x40
github.com/kata-containers/agent/vendor/github.com/opencontainers/runc/libcontainer.(*linuxStandardInit).Init(0x4000141ce0, 0x8, 0x40000100f0)
	/home/jenkins/workspace/kata-containers-tests-ARM-18.04-PR/go/src/github.com/kata-containers/agent/vendor/github.com/opencontainers/runc/libcontainer/standard_init_
linux.go:167 +0x41c
github.com/kata-containers/agent/vendor/github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0x4000150120, 0x0, 0x0)
	/home/jenkins/workspace/kata-containers-tests-ARM-18.04-PR/go/src/github.com/kata-containers/agent/vendor/github.com/opencontainers/runc/libcontainer/factory_linux.
go:321 +0x2ec
main.init.0()
	/home/jenkins/workspace/kata-containers-tests-ARM-18.04-PR/go/src/github.com/kata-containers/agent/agent.go:972 +0x88

r0      0x0
r1      0x7f97c26328
r2      0x0
r3      0x8
r4      0x0
r5      0x7f97c26328
r6      0xffffffffffffffff
r7      0xffffffffffffffff
r8      0x87
r9      0xffffffffffffffff
r10     0xffffffffffffffff
r11     0xffffffffffffffff
r12     0xffffffffffffffff
r13     0xffffffffffffffff
r14     0x8
r15     0x213
r16     0x7f9a6b9458
r17     0x558f149158
r18     0x23f
r19     0x7f9a808000
r20     0x6
r21     0x7f97c26710
r22     0x55bb0f8460
r23     0x1000
r24     0x0
r25     0x7f97c271e0
r26     0x558ecad1b8
r27     0x0
r28     0x4000000f00
r29     0x7f97c26300
lr      0x7f9a6cb90c
sp      0x7f97c26300
pc      0x7f9a6cb97c
fault   0x0
docker: Error response from daemon: OCI runtime start failed: rpc error: code = Unknown desc = cannot start an already running container: unknown.
```

**Comment by jodh-intel** [comment]
Related: #987.

/cc @Pennyzct @Weichen81

**Comment by Pennyzct** [comment]
Hi~ @jodh-intel @devimc it seems working well on my local machine, so I will log into `packet.net ` to see if I can reproduce error there.

**Comment by Pennyzct** [comment]
Hi~ @devimc @jodh-intel [The original failing test case](https://github.com/kata-containers/tests/pull/987#issuecomment-446275883) was limiting data segment as `512000:665600`, which was too small for running a kata-container on aarch64. I see that in new test case, we have already upgraded it to `1024000*1024:2048000*1024`, which will be enough for aarch64.
The output comes from ARM CI machine:
```
root@testing-1:~# docker run --runtime kata-runtime --ulimit data=1048576000:2097152000 -it centos bash -c 'echo "$(ulimit -d -S):$(ulimit -d -H)"'
1024000:2048000
```
I think we can bring back `ulimit -d` test on aarch64. :)

**Comment by devimc** [comment]
@Pennyzct thanks for testing it, I wonder if something is missing in the kernel :thinking:

**Comment by Pennyzct** [comment]
I was quite confused about why two arm machines got different behaviors. 
In my local machine, of course, when the `--ulimit data` value got pretty low, it will output `Cannot allocate memory` error.
But the threshold value is far way smaller than the value needed in ARM CI machine. For example, the value `--ulimit data=512000:665600` and `--ulimit data=102400000:122880000` works well in my local machine, but all outputs error in ARM CI machine.
The have quite the same host kernel, one is `4.20-rc3` and the other is` 4.20-rc4`. I will continue to try to dig the difference, if you have any suggestions to work on, please let me know, thanks! ;) @devimc
